apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcgoonch-deployment
  labels:
    app: grpcgoonch
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpcgoonch
  template:
    metadata:
      labels:
        app: grpcgoonch
    spec:
      containers:
      - name: grpcgoonch
        image: thaigoonch/grpcgoonch:1.2
        ports:
        - containerPort: 9000
---
kind: Service
apiVersion: v1
metadata:
  name: grpcgoonch-service
spec:
  selector:
    app: grpcgoonch
  ports:
    - protocol: TCP
      port: 9000
  type: ClusterIP
  ClusterIP: none
