apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcgoonch-deployment
  labels:
    app: grpcgoonch
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpcgoonch
  template:
    metadata:
      labels:
        app: grpcgoonch
      annotations:
        prometheus.io/port: '2112'
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: grpcgoonch
        image: thaigoonch/grpcgoonch:1.7
        ports:
        - containerPort: 9000
        resources:
          requests:
            memory: "450Mi"
          limits:
            cpu: "0.75"
            memory: "450Mi"
      nodeSelector:
        goonchrole: "server"
---
kind: Service
apiVersion: v1
metadata:
  name: grpcgoonch-service
spec:
  selector:
    app: grpcgoonch
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 80
      targetPort: 9000
