apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcgoonch-deployment
  labels:
    app: grpcgoonch
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpcgoonch
  template:
    metadata:
      labels:
        app: grpcgoonch
      annotations:
        prometheus.io/port: '9092'
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: grpcgoonch
        image: thaigoonch/grpcgoonch:1.12
        ports:
        - name: serviceport
          containerPort: 9000
        resources:
          requests:
            memory: "350Mi"
          limits:
            cpu: "0.70"
            memory: "350Mi"
      nodeSelector:
        goonchrole: "server"
---
kind: Service
apiVersion: v1
metadata:
  name: grpcgoonch-service
  labels:
    app: grpcgoonch
spec:
  selector:
    app: grpcgoonch
  type: ClusterIP
  clusterIP: None
  ports:
  - name: serviceport
    port: 80
    targetPort: 9000
  - name: prometheusport
    port: 9092
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grpcgoonch-servicemonitor
  # Change this to the namespace the Prometheus instance is running in
  namespace: default
  labels:
    app: grpcgoonch
    release: prometheus
spec:
  selector:
    matchLabels:
      app: grpcgoonch # target service
  endpoints:
  - port: prometheusport